# version: '3.8'

# volumes: 
#   postgres_data: 
#   staticfiles: 

# services:
#   db:
#     image: postgres:13.0-alpine
#     volumes:
#       - /var/lib/postgresql/data/
#     env_file:
#       - ./.env

#   web:
#     build: .
#     restart: always
#     ports:
#      - "8000:8000"
#     #  - "8888:8888/udp"

#     depends_on:
#       - "db"
#     env_file:
#       - ./.env

#   nginx: 
#     image: nginx:1.21.3-alpine
#     volumes: 
#       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#       - staticfiles:/code/static/
#     ports: 
#       - 8000:80
#     depends_on: 
#       - web
#     restart: always


version: '3.8'

volumes: 
  postgres_data: 
  staticfiles: 

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    build: .
    restart: always
    ports:
     - "8000:8000"
    #  - "8888:8888/udp"

    depends_on:
      - db
    env_file:
      - ./.env

  nginx: 
    image: nginx:1.21.3-alpine
    volumes: 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - staticfiles:/var/html/static/
    ports: 
      - 8000:80
    depends_on: 
      - web
    restart: always
